### ISSUE TITLE
AutoScroller not exported

### ISSUE THREAD

**Issue by Vluf** [Paol-imi/muuri-react#23]
I'm trying out the "Drag scroll" feature, but AutoScroller is not exported from muuri-react.
The examples "pokedex" and "scroll" do not work due to this. I'm not able to get the drag scroll feature working, as shown on the README.
I noticed the values here: https://github.com/Paol-imi/muuri-react/blob/master/src/muuri.d.ts
Setting them manually does not fix the issue, however.

I also noticed the examples all use muuri^0.9.0, which is an unreleased version. This might be the cause?

**Comment by Vluf** [comment]
This seems to be an issue do to muuri^0.9.0 not being released yet, as installing the dev muuri branch made it all work.
See https://github.com/haltu/muuri/issues/373 for progress

**Comment by Paol-imi** [comment]
I developed this version of muuri-react to support the new features that will be available with muuri 0.9.0 (which is currently under development). The initial plan was to bring out the two packages simultaneously.

I finished this version earlier than expected, and since it contained some fixes, I decided to publish it anyway by hiding everything (or almost) that related to muuri 0.9.0 from the documentation.

I left the examples in case anyone was interested in testing them using muuri 0.9.0 before it is officially released.

When the new version is available I will upload the new documentation and update the examples.
