### ISSUE TITLE
Container has zero height in horizontal layout

### ISSUE THREAD

**Issue by ftruzzi** [Paol-imi/muuri-react#35]
Ciao, and thank you for your work!

I'm trying to get muuri-react to work with my project and am experiencing an issue with horizontal layout. Not sure if it's a bug, as I'm very new to web development and might be missing something.

Basically, when enabling the horizontal layout option, the container has zero height and I can't add any text at the bottom.

Example: https://codesandbox.io/s/muuri-react-kanban-detv8?file=/index.js (I added a "This should be below" div that I want to stay below the kanban board)

How do I make sure the container has the correct height?

Thanks :)

**Comment by Paol-imi** [comment]
Ciao Francesco,

In your example the main MuuriComponent is setting its height to 0 as if it had no elements inside it, and therefore your div is displayed immediately afterwards. I believe this problem is due to some wrong style/setting and not a bug.

Try creating another fork of the kanban demo and inserting the div, without making any other changes.

If the problem persists I will investigate further.

**Comment by ftruzzi** [comment]
> Try creating another fork of the kanban demo and inserting the div, without making any other changes.

That's the only change I made: it works correctly when passing no layout props to the MuuriComponent, but as soon as I add `layout={{horizontal: true}}` (since I want my items to stay on the same line) the MuuriComponent has zero height.

Forcing a specific height via CSS classes works, but maybe it should be detected automatically based on the tallest item?

**Comment by Paol-imi** [comment]
My fault, I misunderstood your problem.

When you use the vertical layout, Muuri relies on the width of the element to decide the position of the items and therefore adjust the height of the element. The same happens with the horizontal layout, but with inverted height and width.

In that example, the div created by the MuuriCompoennt has height 0 initially, if the layout is vertical Muuri calculates that height, if the layout is horizontal, Muuri expects that the height is the one you want to use.

My fault, I misunderstood your problem.

When you use the vertical layout, Muuri relies on the width of the element to decide the position of the items and therefore adjust the height of the element.

The same happens with the horizontal layout, but with inverted height and width.

In that example, the div created by the MuuriCompoennt has height 0 initially, if the layout is vertical Muuri calculates that height, if the layout is horizontal, Muuri expects that the height is the one you want to use.

> Forcing a specific height via CSS classes works, but maybe it should be detected automatically based on the tallest item?

It may seem unintuitive because you are using vertical layout grids inside a horizontal layout grid, but yes, you have to set the height.
