### ISSUE TITLE
Certain items not collapsing

### ISSUE THREAD

**Issue by beamercola** [Paol-imi/muuri-react#40]
Wow, this library is awesome, thank you.

I'm having a weird thing happen where sometimes whitespace will collapse and sometimes it doesn't.  If you resize a bit it fixes itself but it's hit and miss every time

<img width="1066" alt="Screen Shot 2020-06-30 at 10 16 11 PM" src="https://user-images.githubusercontent.com/8060/86205727-789a9b80-bb1f-11ea-93d5-dbf38e378d62.png">
(red squiggle was added for dramatics)

My code (I just added `fillGaps` as a test, no change)
```
<MuuriComponent instantLayout layout={{ fillGaps: true }}>
  {content}
</MuuriComponent>
```

**Comment by Paol-imi** [comment]
Hi beamercola,

This is probably due to the fact that you are using Muuri 0.8.0 with relative item sizes (e.g. 30%).
That version does not work well in these situations so you can update it to 0.9.0.

For more information on responsive layout see [here](https://paol-imi.github.io/muuri-react/docs/usage/responsive-style)
