### ISSUE TITLE
Element.animate is not a function

### ISSUE THREAD

**Issue by et-nat1995** [Paol-imi/muuri-react#7]
I have been playing around with this package and seems pretty promising. Although i wanted to test my project out on iOS devices and nothing would render. Getting this error: 
<img width="413" alt="Screen Shot 2020-03-09 at 12 52 09 PM" src="https://user-images.githubusercontent.com/42855538/76251873-06ffb000-6205-11ea-94d3-6e45d42ab39f.png">

To make sure its not only my project i checked the examples in your docs [Grid Example](https://codesandbox.io/s/muuri-react-grid-1czo5)

Another question. Im using Material-UI in my project and i would like to use MUI components and styles with this package, is there a way to use other components and wrap them with this package?

**Comment by Paol-imi** [comment]
Hi et-nat1995,

As you may know Muuri uses [**Web Animations**](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) to handle all the animations by default. There may be 2 cases:

-  If your project doesn't even open and shows the error, it is very likely that your broswer does not support web animations and you need a [**polyfill**](https://github.com/web-animations/web-animations-js). You can check if your broswer supports them [**here**](https://caniuse.com/#feat=web-animation).
- There is a known [**bug**](https://github.com/haltu/muuri/issues/359) in [**Muuri**](https://github.com/haltu/muuri) in its version 0.8.0 (it will be fixed in version 0.9.0 when it is published). This bug occurs in the **Grid** demo, it happens if you apply a filter (e.g. 'red') and try to drag an element.

Thanks for the appreciation of the library, update me when you discover the problem.
